### ISSUE TITLE
I cannot find get_it_container.config.dart file

### ISSUE THREAD

**Issue by CharlesEBBarros** [yunusemrealpak/flutter_onion_architecture#4]
This file is mentioned [here](https://github.com/yunusemrealpak/flutter_onion_architecture/blob/1c6d412622ed2bbb73171b68e6114d1e325b7b2e/lib/di/injection/get_it_container.dart#L5), but it's not available on main.

Could you help with this, please?

Thanks.

**Comment by yunusemrealpak** [comment]
Hello,

To generate the necessary code using build_runner, please run the following command in your terminal:

```
dart run build_runner build --delete-conflicting-outputs
```
This command will generate the required files and resolve any conflicting outputs.

Hope this helps!

**Comment by yunusemrealpak** [comment]
Hello,

To generate the necessary code using build_runner, please run the following command in your terminal:

```
dart run build_runner build --delete-conflicting-outputs
```

This command will generate the required files and resolve any conflicting outputs.

Hope this helps!

**Comment by CharlesEBBarros** [comment]
Hi @yunusemrealpak,
Thanks for your quick response. I'm still facing problems with GetIt.
Could you help me, please?

`lib/main.dart:14:24: Error: This expression has type 'void' and can't be used.
  await GetItContainer.configureDependencies();
                       ^
lib/main.dart:17:28: Error: This expression has type 'void' and can't be used.
  await MediatorInjector().subscribe(GetItContainer.instance);
                           ^
lib/di/injection/get_it_container.config.dart:75:21: Error: Type argument 'dynamic' doesn't conform to the bound 'Object' of the type variable 'T' on 'GetItHelper.call'.
 - 'Object' is from 'dart:core'.
 - 'GetItHelper' is from 'package:injectable/src/get_it_helper.dart' ('/home/charlesb/.pub-cache/hosted/pub.dev/injectable-2.5.0/lib/src/get_it_helper.dart').
Try changing type arguments so that they conform to the bounds.
          entity: gh<dynamic>(),
                    ^
lib/di/injection/get_it_container.config.dart:76:20: Error: Type argument 'dynamic' doesn't conform to the bound 'Object' of the type variable 'T' on 'GetItHelper.call'.
 - 'Object' is from 'dart:core'.
 - 'GetItHelper' is from 'package:injectable/src/get_it_helper.dart' ('/home/charlesb/.pub-cache/hosted/pub.dev/injectable-2.5.0/lib/src/get_it_helper.dart').
Try changing type arguments so that they conform to the bounds.
          error: gh<dynamic>(),
                   ^
lib/infrastructure/persistence/repositories/product_repository.dart:15:11: Error: A value of type 'String' can't be assigned to a variable of type 'GenericRepoMethod'.
 - 'GenericRepoMethod' is from 'package:flutter_onion_architecture/common/extensions/generic_repo_method.dart' ('lib/common/extensions/generic_repo_method.dart').
          "getAll": "/api/product/getAll",
          ^
lib/infrastructure/persistence/repositories/product_repository.dart:16:11: Error: A value of type 'String' can't be assigned to a variable of type 'GenericRepoMethod'.
 - 'GenericRepoMethod' is from 'package:flutter_onion_architecture/common/extensions/generic_repo_method.dart' ('lib/common/extensions/generic_repo_method.dart').
          "getById": "/api/product/getById",
          ^
lib/core/application/features/product/queries/get_all_product/get_all_product_query_handler.dart:22:38: Error: The argument type 'Failure?' can't be assigned to the parameter type 'Failure' because 'Failure?' is nullable and 'Failure' isn't.
 - 'Failure' is from 'package:busenet/src/models/failure/failure.dart' ('/home/charlesb/.pub-cache/hosted/pub.dev/busenet-0.9.1/lib/src/models/failure/failure.dart').
      (l) => ServiceResponse.failure(l),
                                     ^
lib/core/application/features/product/commands/create_product/create_product_command_handler.dart:31:38: Error: The argument type 'Failure?' can't be assigned to the parameter type 'Failure' because 'Failure?' is nullable and 'Failure' isn't.
 - 'Failure' is from 'package:busenet/src/models/failure/failure.dart' ('/home/charlesb/.pub-cache/hosted/pub.dev/busenet-0.9.1/lib/src/models/failure/failure.dart').
      (l) => ServiceResponse.failure(l),
                                     ^
                                     ^
                                     ^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

                                     ^
Target kernel_snapshot_program failed: Exception


                                     ^
Target kernel_snapshot_program failed: Exception


                                     ^
Target kernel_snapshot_program failed: Exception


Target kernel_snapshot_program failed: Exception



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/charlesb/Applications/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleDebug'...                              3.9s
Error: Gradle task assembleDebug failed with exit code 1`

**Comment by yunusemrealpak** [comment]
Hello again,

There was a problem with dynamic fields in ResponseModel, solved. Thank you for the feedback

Can you run build_runner and try again
